"""Initial schema: users, games, game_players, events

Revision ID: d43ac692df4f
Revises: 
Create Date: 2026-08-05 18:23:52.524633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd43ac692df4f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('WAITING_FOR_PLAYERS', 'IN_PROGRESS', 'COMPLETED', 'ABANDONED', name='gamestatus'), nullable=False),
    sa.Column('turn_direction', sa.Enum('CLOCKWISE', 'COUNTERCLOCKWISE', name='turndirection'), nullable=False),
    sa.Column('current_round', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('events',
    sa.Column('event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('round_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('turn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('GAME_STARTED', 'ROUND_STARTED', 'INITIAL_GLANCE', 'ROUND_ENDED', 'SCORES_UPDATED', 'RENAISSANCE_TRIGGERED', 'GAME_ENDED', 'CARD_DRAWN', 'ACTION_TAKEN', 'SPELL_INVOCATION_DECISION', 'SPELL_REVEALED', 'SPELL_SWAP_DECISION', 'QUICK_DISCARD_PLAYED', 'TESTIMONY_GIVEN', 'TESTIMONY_WINDOW_PASSED', 'CHALLENGE_GIVEN', 'CHALLENGE_WINDOW_PASSED', 'VERDICT_RESOLVED', 'DUEL_RESOLVED', 'PLEA_TAKEN', 'PLEA_WINDOW_PASSED', 'HAND_EMPTIED', name='eventtype'), nullable=False),
    sa.Column('actor_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('public_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('scoped_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['actor_uuid'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('event_id'),
    sa.UniqueConstraint('game_id', 'sequence', name='uq_event_game_sequence')
    )
    op.create_index(op.f('ix_events_game_id'), 'events', ['game_id'], unique=False)
    op.create_index(op.f('ix_events_round_id'), 'events', ['round_id'], unique=False)
    op.create_index(op.f('ix_events_sequence'), 'events', ['sequence'], unique=False)
    op.create_index(op.f('ix_events_type'), 'events', ['type'], unique=False)
    op.create_table('game_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_uuid', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seat_order', sa.Integer(), nullable=False),
    sa.Column('current_score', sa.Integer(), nullable=False),
    sa.Column('final_rank', sa.Integer(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_uuid'], ['users.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'seat_order', name='uq_game_player_seat'),
    sa.UniqueConstraint('game_id', 'user_uuid', name='uq_game_player_user')
    )
    op.create_index(op.f('ix_game_players_game_id'), 'game_players', ['game_id'], unique=False)
    op.create_index(op.f('ix_game_players_user_uuid'), 'game_players', ['user_uuid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_players_user_uuid'), table_name='game_players')
    op.drop_index(op.f('ix_game_players_game_id'), table_name='game_players')
    op.drop_table('game_players')
    op.drop_index(op.f('ix_events_type'), table_name='events')
    op.drop_index(op.f('ix_events_sequence'), table_name='events')
    op.drop_index(op.f('ix_events_round_id'), table_name='events')
    op.drop_index(op.f('ix_events_game_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('games')
    # ### end Alembic commands ###
